version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  galaxy: requirements.yml
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
additional_build_steps:
  prepend_base:
    - "RUN dnf install -y gcc make python3-devel && dnf clean all"
    - "RUN pip3 install --upgrade pip setuptools wheel"
